# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6115-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter citrus lime,$(TARGET_DEVICE)),)

endif
